language: node_js
node_js:
- 12.16.1

addons:
  ssh_known_hosts:
    - live.a11radio.com

dist: trusty
sudo: false

before_install:
- openssl aes-256-cbc -K $encrypted_aebfdddc2359_key -iv $encrypted_aebfdddc2359_iv
  -in gatsby-deploy.enc -out gatsby-deploy -d
- eval "$(ssh-agent -s)"
- cp scripts/gatsby-deploy ~/.ssh/gatsby-deploy
- chmod 600 ~/.ssh/gatsby-deploy
- ssh-add ~/.ssh/gatsby-deploy
- echo -e "Host live.a11radio.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
